spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: ssafy_trip_batch
  batch:
    job:
      enabled: false # job ?? ??
    jdbc:
      initialize-schema: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:32769/ssafy_trip_batch?rewriteBatchedStatements=true
    username: root
    password: zxcvb2
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true
logging:
  level:
    org.springframework.jdbc: DEBUG
springdoc:
  swagger-ui:
    path: /docs
---

