spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: ssafy_trip_batch
  batch:
    job:
      enabled: false # job ?? ??
    jdbc:
      initialize-schema: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:32769/ssafy_trip_batch?rewriteBatchedStatements=true
    username: root
    password: zxcvb2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jackson:
    deserialization:
      accept-empty-string-as-null-object: true
logging:
  level:
    org.springframework.jdbc.core: DEBUG # Spring JDBC ?? ??? ?? ??
    org.springframework.jdbc.datasource: DEBUG # ??? ??? ??? ??
    org.springframework.jdbc.support: TRACE # SQL ?? ?? ???? ??? ??
    org.hibernate.SQL: DEBUG # Hibernate SQL ?? (JPA ?? ?)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL ???? ??? ??
springdoc:
  swagger-ui:
    path: /docs
---

